/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) mpcc_qcar2_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {4, 1, 1};
static const casadi_int casadi_s1[3] = {4, 4, 1};
static const casadi_int casadi_s2[3] = {4, 3, 1};
static const casadi_int casadi_s3[3] = {3, 1, 1};
static const casadi_int casadi_s4[3] = {20, 1, 1};

/* mpcc_qcar2_expl_vde_forw:(i0[4],i1[4x4],i2[4x3],i3[3],i4[20])->(o0[4],o1[4x4],o2[4x3]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13;
  a00=arg[3]? arg[3][0] : 0;
  a01=arg[0]? arg[0][2] : 0;
  a02=arg[3]? arg[3][1] : 0;
  a03=tan(a02);
  a04=2.;
  a04=(a03/a04);
  a05=atan(a04);
  a01=(a01+a05);
  a06=cos(a01);
  a07=(a00*a06);
  if (res[0]!=0) res[0][0]=a07;
  a01=sin(a01);
  a07=(a00*a01);
  if (res[0]!=0) res[0][1]=a07;
  a07=2.5600000000000001e-01;
  a07=(a00/a07);
  a08=(a07*a03);
  a09=cos(a05);
  a10=(a08*a09);
  if (res[0]!=0) res[0][2]=a10;
  a10=arg[3]? arg[3][2] : 0;
  if (res[0]!=0) res[0][3]=a10;
  a10=arg[1]? arg[1][2] : 0;
  a11=(a01*a10);
  a11=(a00*a11);
  a11=(-a11);
  if (res[1]!=0) res[1][0]=a11;
  a10=(a06*a10);
  a10=(a00*a10);
  if (res[1]!=0) res[1][1]=a10;
  a10=0.;
  if (res[1]!=0) res[1][2]=a10;
  if (res[1]!=0) res[1][3]=a10;
  a11=arg[1]? arg[1][6] : 0;
  a12=(a01*a11);
  a12=(a00*a12);
  a12=(-a12);
  if (res[1]!=0) res[1][4]=a12;
  a11=(a06*a11);
  a11=(a00*a11);
  if (res[1]!=0) res[1][5]=a11;
  if (res[1]!=0) res[1][6]=a10;
  if (res[1]!=0) res[1][7]=a10;
  a11=arg[1]? arg[1][10] : 0;
  a12=(a01*a11);
  a12=(a00*a12);
  a12=(-a12);
  if (res[1]!=0) res[1][8]=a12;
  a11=(a06*a11);
  a11=(a00*a11);
  if (res[1]!=0) res[1][9]=a11;
  if (res[1]!=0) res[1][10]=a10;
  if (res[1]!=0) res[1][11]=a10;
  a11=arg[1]? arg[1][14] : 0;
  a12=(a01*a11);
  a12=(a00*a12);
  a12=(-a12);
  if (res[1]!=0) res[1][12]=a12;
  a11=(a06*a11);
  a11=(a00*a11);
  if (res[1]!=0) res[1][13]=a11;
  if (res[1]!=0) res[1][14]=a10;
  if (res[1]!=0) res[1][15]=a10;
  a11=arg[2]? arg[2][2] : 0;
  a12=(a01*a11);
  a12=(a00*a12);
  a12=(a06-a12);
  if (res[2]!=0) res[2][0]=a12;
  a11=(a06*a11);
  a11=(a00*a11);
  a11=(a01+a11);
  if (res[2]!=0) res[2][1]=a11;
  a11=3.9062500000000000e+00;
  a11=(a11*a03);
  a11=(a09*a11);
  if (res[2]!=0) res[2][2]=a11;
  if (res[2]!=0) res[2][3]=a10;
  a11=5.0000000000000000e-01;
  a02=cos(a02);
  a02=casadi_sq(a02);
  a11=(a11/a02);
  a03=1.;
  a04=casadi_sq(a04);
  a04=(a03+a04);
  a11=(a11/a04);
  a04=(a01*a11);
  a04=(a00*a04);
  a12=arg[2]? arg[2][6] : 0;
  a13=(a01*a12);
  a13=(a00*a13);
  a04=(a04+a13);
  a04=(-a04);
  if (res[2]!=0) res[2][4]=a04;
  a04=(a06*a11);
  a04=(a00*a04);
  a12=(a06*a12);
  a12=(a00*a12);
  a04=(a04+a12);
  if (res[2]!=0) res[2][5]=a04;
  a07=(a07/a02);
  a09=(a09*a07);
  a05=sin(a05);
  a05=(a05*a11);
  a08=(a08*a05);
  a09=(a09-a08);
  if (res[2]!=0) res[2][6]=a09;
  if (res[2]!=0) res[2][7]=a10;
  a09=arg[2]? arg[2][10] : 0;
  a01=(a01*a09);
  a01=(a00*a01);
  a01=(-a01);
  if (res[2]!=0) res[2][8]=a01;
  a06=(a06*a09);
  a00=(a00*a06);
  if (res[2]!=0) res[2][9]=a00;
  if (res[2]!=0) res[2][10]=a10;
  if (res[2]!=0) res[2][11]=a03;
  return 0;
}

CASADI_SYMBOL_EXPORT int mpcc_qcar2_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int mpcc_qcar2_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int mpcc_qcar2_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mpcc_qcar2_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int mpcc_qcar2_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mpcc_qcar2_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void mpcc_qcar2_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void mpcc_qcar2_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int mpcc_qcar2_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int mpcc_qcar2_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real mpcc_qcar2_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mpcc_qcar2_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mpcc_qcar2_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mpcc_qcar2_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mpcc_qcar2_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int mpcc_qcar2_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int mpcc_qcar2_expl_vde_forw_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
