/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) mpcc_qcar2_expl_ode_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {4, 1, 1};
static const casadi_int casadi_s1[3] = {4, 4, 1};
static const casadi_int casadi_s2[3] = {4, 3, 1};
static const casadi_int casadi_s3[3] = {3, 1, 1};
static const casadi_int casadi_s4[3] = {20, 1, 1};
static const casadi_int casadi_s5[3] = {7, 1, 1};
static const casadi_int casadi_s6[3] = {28, 1, 1};

/* mpcc_qcar2_expl_ode_hess:(i0[4],i1[4x4],i2[4x3],i3[4],i4[3],i5[20])->(o0[7],o1[28]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31;
  a00=0.;
  if (res[0]!=0) res[0][0]=a00;
  if (res[0]!=0) res[0][1]=a00;
  a01=arg[0]? arg[0][2] : 0;
  a02=arg[4]? arg[4][1] : 0;
  a03=tan(a02);
  a04=2.;
  a04=(a03/a04);
  a05=atan(a04);
  a01=(a01+a05);
  a06=cos(a01);
  a07=arg[4]? arg[4][0] : 0;
  a08=arg[3]? arg[3][1] : 0;
  a09=(a07*a08);
  a10=(a06*a09);
  a01=sin(a01);
  a11=arg[3]? arg[3][0] : 0;
  a12=(a07*a11);
  a13=(a01*a12);
  a14=(a10-a13);
  if (res[0]!=0) res[0][2]=a14;
  if (res[0]!=0) res[0][3]=a00;
  a00=3.9062500000000000e+00;
  a14=cos(a05);
  a15=arg[3]? arg[3][2] : 0;
  a16=(a14*a15);
  a17=(a03*a16);
  a17=(a00*a17);
  a18=(a01*a08);
  a17=(a17+a18);
  a18=(a06*a11);
  a17=(a17+a18);
  if (res[0]!=0) res[0][4]=a17;
  a17=2.5600000000000001e-01;
  a07=(a07/a17);
  a17=(a07*a16);
  a18=cos(a02);
  a19=casadi_sq(a18);
  a17=(a17/a19);
  a20=5.0000000000000000e-01;
  a05=sin(a05);
  a21=(a07*a03);
  a21=(a21*a15);
  a22=(a05*a21);
  a10=(a10-a22);
  a10=(a10-a13);
  a13=1.;
  a04=casadi_sq(a04);
  a13=(a13+a04);
  a10=(a10/a13);
  a04=(a20*a10);
  a04=(a04/a19);
  a22=(a17+a04);
  if (res[0]!=0) res[0][5]=a22;
  a22=arg[3]? arg[3][3] : 0;
  if (res[0]!=0) res[0][6]=a22;
  a22=arg[1]? arg[1][2] : 0;
  a23=(a01*a22);
  a24=(a09*a23);
  a25=(a06*a22);
  a26=(a12*a25);
  a24=(a24+a26);
  a22=(a22*a24);
  a22=(-a22);
  if (res[1]!=0) res[1][0]=a22;
  a22=arg[1]? arg[1][6] : 0;
  a26=(a22*a24);
  a26=(-a26);
  if (res[1]!=0) res[1][1]=a26;
  a26=arg[1]? arg[1][10] : 0;
  a27=(a26*a24);
  a27=(-a27);
  if (res[1]!=0) res[1][2]=a27;
  a27=arg[1]? arg[1][14] : 0;
  a28=(a27*a24);
  a28=(-a28);
  if (res[1]!=0) res[1][3]=a28;
  a25=(a08*a25);
  a23=(a11*a23);
  a25=(a25-a23);
  a23=arg[2]? arg[2][2] : 0;
  a28=(a23*a24);
  a25=(a25-a28);
  if (res[1]!=0) res[1][4]=a25;
  a25=arg[2]? arg[2][6] : 0;
  a28=(a25*a24);
  a29=(a24/a13);
  a29=(a20*a29);
  a29=(a29/a19);
  a28=(a28+a29);
  a28=(-a28);
  if (res[1]!=0) res[1][5]=a28;
  a28=arg[2]? arg[2][10] : 0;
  a24=(a28*a24);
  a24=(-a24);
  if (res[1]!=0) res[1][6]=a24;
  a24=(a01*a22);
  a29=(a09*a24);
  a30=(a06*a22);
  a31=(a12*a30);
  a29=(a29+a31);
  a22=(a22*a29);
  a22=(-a22);
  if (res[1]!=0) res[1][7]=a22;
  a22=(a26*a29);
  a22=(-a22);
  if (res[1]!=0) res[1][8]=a22;
  a22=(a27*a29);
  a22=(-a22);
  if (res[1]!=0) res[1][9]=a22;
  a30=(a08*a30);
  a24=(a11*a24);
  a30=(a30-a24);
  a24=(a23*a29);
  a30=(a30-a24);
  if (res[1]!=0) res[1][10]=a30;
  a30=(a25*a29);
  a24=(a29/a13);
  a24=(a20*a24);
  a24=(a24/a19);
  a30=(a30+a24);
  a30=(-a30);
  if (res[1]!=0) res[1][11]=a30;
  a29=(a28*a29);
  a29=(-a29);
  if (res[1]!=0) res[1][12]=a29;
  a29=(a01*a26);
  a30=(a09*a29);
  a24=(a06*a26);
  a22=(a12*a24);
  a30=(a30+a22);
  a26=(a26*a30);
  a26=(-a26);
  if (res[1]!=0) res[1][13]=a26;
  a26=(a27*a30);
  a26=(-a26);
  if (res[1]!=0) res[1][14]=a26;
  a24=(a08*a24);
  a29=(a11*a29);
  a24=(a24-a29);
  a29=(a23*a30);
  a24=(a24-a29);
  if (res[1]!=0) res[1][15]=a24;
  a24=(a25*a30);
  a29=(a30/a13);
  a29=(a20*a29);
  a29=(a29/a19);
  a24=(a24+a29);
  a24=(-a24);
  if (res[1]!=0) res[1][16]=a24;
  a30=(a28*a30);
  a30=(-a30);
  if (res[1]!=0) res[1][17]=a30;
  a30=(a01*a27);
  a24=(a09*a30);
  a29=(a06*a27);
  a26=(a12*a29);
  a24=(a24+a26);
  a27=(a27*a24);
  a27=(-a27);
  if (res[1]!=0) res[1][18]=a27;
  a29=(a08*a29);
  a30=(a11*a30);
  a29=(a29-a30);
  a30=(a23*a24);
  a29=(a29-a30);
  if (res[1]!=0) res[1][19]=a29;
  a29=(a25*a24);
  a30=(a24/a13);
  a30=(a20*a30);
  a30=(a30/a19);
  a29=(a29+a30);
  a29=(-a29);
  if (res[1]!=0) res[1][20]=a29;
  a24=(a28*a24);
  a24=(-a24);
  if (res[1]!=0) res[1][21]=a24;
  a24=(a06*a08);
  a29=(a01*a23);
  a30=(a09*a29);
  a24=(a24-a30);
  a30=(a06*a23);
  a27=(a12*a30);
  a26=(a01*a11);
  a27=(a27+a26);
  a26=(a24-a27);
  a23=(a23*a26);
  a08=(a08*a30);
  a11=(a11*a29);
  a08=(a08-a11);
  a23=(a23+a08);
  if (res[1]!=0) res[1][22]=a23;
  a23=(a25*a26);
  a16=(a00*a16);
  a16=(a16/a19);
  a00=(a00*a03);
  a00=(a15*a00);
  a00=(a05*a00);
  a24=(a24-a00);
  a24=(a24-a27);
  a24=(a24/a13);
  a24=(a20*a24);
  a24=(a24/a19);
  a16=(a16+a24);
  a23=(a23+a16);
  if (res[1]!=0) res[1][23]=a23;
  a26=(a28*a26);
  if (res[1]!=0) res[1][24]=a26;
  a17=(a17/a19);
  a18=(a18+a18);
  a02=sin(a02);
  a18=(a18*a02);
  a17=(a17*a18);
  a02=(a20/a19);
  a26=(a02/a13);
  a23=(a05*a26);
  a23=(a15*a23);
  a23=(a07*a23);
  a23=(a23/a19);
  a17=(a17-a23);
  a04=(a04/a19);
  a04=(a04*a18);
  a18=(a25+a26);
  a23=(a01*a18);
  a23=(a09*a23);
  a14=(a14*a26);
  a21=(a21*a14);
  a07=(a07/a19);
  a15=(a15*a07);
  a05=(a05*a15);
  a21=(a21+a05);
  a21=(a23+a21);
  a18=(a06*a18);
  a18=(a12*a18);
  a21=(a21+a18);
  a21=(a21/a13);
  a10=(a10/a13);
  a03=(a03*a02);
  a10=(a10*a03);
  a21=(a21+a10);
  a20=(a20*a21);
  a20=(a20/a19);
  a04=(a04-a20);
  a17=(a17+a04);
  a23=(a23+a18);
  a25=(a25*a23);
  a17=(a17-a25);
  if (res[1]!=0) res[1][25]=a17;
  a23=(a28*a23);
  a23=(-a23);
  if (res[1]!=0) res[1][26]=a23;
  a01=(a01*a28);
  a09=(a09*a01);
  a06=(a06*a28);
  a12=(a12*a06);
  a09=(a09+a12);
  a28=(a28*a09);
  a28=(-a28);
  if (res[1]!=0) res[1][27]=a28;
  return 0;
}

CASADI_SYMBOL_EXPORT int mpcc_qcar2_expl_ode_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int mpcc_qcar2_expl_ode_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int mpcc_qcar2_expl_ode_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mpcc_qcar2_expl_ode_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int mpcc_qcar2_expl_ode_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mpcc_qcar2_expl_ode_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void mpcc_qcar2_expl_ode_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void mpcc_qcar2_expl_ode_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int mpcc_qcar2_expl_ode_hess_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int mpcc_qcar2_expl_ode_hess_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real mpcc_qcar2_expl_ode_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mpcc_qcar2_expl_ode_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mpcc_qcar2_expl_ode_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mpcc_qcar2_expl_ode_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s0;
    case 4: return casadi_s3;
    case 5: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mpcc_qcar2_expl_ode_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    case 1: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int mpcc_qcar2_expl_ode_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int mpcc_qcar2_expl_ode_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
