/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) mpcc_qcar2_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {4, 1, 1};
static const casadi_int casadi_s1[3] = {3, 1, 1};
static const casadi_int casadi_s2[3] = {20, 1, 1};
static const casadi_int casadi_s3[3] = {7, 1, 1};

/* mpcc_qcar2_expl_vde_adj:(i0[4],i1[4],i2[3],i3[20])->(o0[7]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14;
  a00=0.;
  if (res[0]!=0) res[0][0]=a00;
  if (res[0]!=0) res[0][1]=a00;
  a01=arg[0]? arg[0][2] : 0;
  a02=arg[2]? arg[2][1] : 0;
  a03=tan(a02);
  a04=2.;
  a04=(a03/a04);
  a05=atan(a04);
  a01=(a01+a05);
  a06=cos(a01);
  a07=arg[2]? arg[2][0] : 0;
  a08=arg[1]? arg[1][1] : 0;
  a09=(a07*a08);
  a09=(a06*a09);
  a01=sin(a01);
  a10=arg[1]? arg[1][0] : 0;
  a11=(a07*a10);
  a11=(a01*a11);
  a12=(a09-a11);
  if (res[0]!=0) res[0][2]=a12;
  if (res[0]!=0) res[0][3]=a00;
  a00=3.9062500000000000e+00;
  a12=cos(a05);
  a13=arg[1]? arg[1][2] : 0;
  a12=(a12*a13);
  a14=(a03*a12);
  a00=(a00*a14);
  a01=(a01*a08);
  a00=(a00+a01);
  a06=(a06*a10);
  a00=(a00+a06);
  if (res[0]!=0) res[0][4]=a00;
  a00=2.5600000000000001e-01;
  a07=(a07/a00);
  a12=(a07*a12);
  a02=cos(a02);
  a02=casadi_sq(a02);
  a12=(a12/a02);
  a00=5.0000000000000000e-01;
  a05=sin(a05);
  a07=(a07*a03);
  a07=(a07*a13);
  a05=(a05*a07);
  a09=(a09-a05);
  a09=(a09-a11);
  a11=1.;
  a04=casadi_sq(a04);
  a11=(a11+a04);
  a09=(a09/a11);
  a00=(a00*a09);
  a00=(a00/a02);
  a12=(a12+a00);
  if (res[0]!=0) res[0][5]=a12;
  a12=arg[1]? arg[1][3] : 0;
  if (res[0]!=0) res[0][6]=a12;
  return 0;
}

CASADI_SYMBOL_EXPORT int mpcc_qcar2_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int mpcc_qcar2_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int mpcc_qcar2_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mpcc_qcar2_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int mpcc_qcar2_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mpcc_qcar2_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void mpcc_qcar2_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void mpcc_qcar2_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int mpcc_qcar2_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int mpcc_qcar2_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real mpcc_qcar2_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mpcc_qcar2_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mpcc_qcar2_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mpcc_qcar2_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mpcc_qcar2_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int mpcc_qcar2_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int mpcc_qcar2_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
